### ISSUE TITLE
Heartbeat updates sometimes dying until cnapi is restarted

### ISSUE THREAD

**Issue by KrisShannon** [joyent/sdc-cnapi#7]
I think it's related to 060a7b8d5d (CNAPI-645: streamline handling of and updating) and the rewrite of onHeartbeat.

If the timeout logic is ever invoked and writeNext gets called it sets .current and then calls onHeartbeat which sees .current is set and bails...

**Comment by KrisShannon** [comment]
This ( AmazeCom/sdc-cnapi@3376cbcfed - WIP Hack attempt to fix heartbeat timeout logic ) seems to fix it.

I added an outgoing firewall drop rule for port 2020 (to moray) and started seeing the "already writing heartbeat from ..." in the logs.   I then disabled the firewall and it recovered fine without needing a restart.

I didn't make a pull request as it needs to be rewritten cleaner.

**Comment by rmustacc** [comment]
@orlandov if you have a chance can you take a look at this?

**Comment by orlandov** [comment]
Hey +KrisShannon, first of all apologies, I don't often look at the Github issues and must have missed a notification that you submitted this.

Is this misbehaviour something you're still seeing in the current code? I have some changes to the logic around heartbeats to address this problem in the months since you submitted this. Would be curious to know if you are still experiencing this problem. Thanks again and sorry for not having seen this earlier!

**Comment by KrisShannon** [comment]
Back in May we were working with a small Lab deployment of Triton.

Since then we have setup a completely new Triton deployment for production.

Because the headnode has much bigger RAM, and CPU we haven't encountered the problem under normal operation.

I did try to replicate using the firewall trick I used before:

    FROM vm CNAPI-UUID TO tag smartdc_role=moray BLOCK tcp PORT all

I am currently running cnapi release-20160818-20160818T182736Z-g550a06b.

It recovered correctly when I disabled the firewall rule so I think this can be marked fixed.
